return [
  {
    href: 'https://designrevision.com/docs/shards-react/component/alert',
    title: 'Alert',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'tag',
        description: 'The component tag type.',
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'dismissible',
        description: 'Whether is dismissible, or not.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: 'primary',
        propTypeIsRequired: false,
      },
      {
        title: 'open',
        description: 'Whether is open, or not.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'closeAriaLabel',
        description: "The close button's aria label.",
        propTypeProp: 'string',
        propTypeVal: 'Close',
        propTypeIsRequired: false,
      },
      {
        title: 'closeClassName',
        description: "The close button's class name.",
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'fade',
        description: 'Whether it should fade, or not.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'transition',
        description:
          'The transition config. See `Fade` component for more details.',
        propTypeProp: 'Shape',
        propTypeVal: '{\n  ...Fade.defaultProps,\n  unmountOnExit: true\n}',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    href: 'https://designrevision.com/docs/shards-react/component/container',
    title: 'Container',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'fluid',
        description: 'Whether it is fluid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'FuncString',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    href: 'https://designrevision.com/docs/shards-react/component/container',
    title: 'Row',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'noGutters',
        description: 'Whether it has gutters, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'form',
        description: 'Whether it is located inside a form, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'FuncString',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    href: 'https://designrevision.com/docs/shards-react/component/container',
    title: 'Col',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'breakpoints',
        description: 'The available breakpoints.',
        propTypeProp: 'Array',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'FuncString',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'xs',
        description: 'Col number or config object for xs viewports.',
        propTypeProp: 'any',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'sm',
        description: 'Col number or config object for sm viewports.',
        propTypeProp: 'any',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'md',
        description: 'Col number or config object for md viewports.',
        propTypeProp: 'any',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'lg',
        description: 'Col number or config object for lg viewports.',
        propTypeProp: 'any',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'xl',
        description: 'Col number or config object for xl viewports.',
        propTypeProp: 'any',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Popover',
    href: 'https://designrevision.com/docs/shards-react/component/popover',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'offset',
        description: 'The popover offset.',
        propTypeProp: 'StringNumber',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'container',
        description: 'The popover container.',
        propTypeProp: 'Custom',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerClassName',
        description: 'The inner class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'toggle',
        description: 'The toggle function.',
        propTypeProp: 'function',
        propTypeVal: 'function() {}',
        propTypeIsRequired: false,
      },
      {
        title: 'delay',
        description: 'The show/hide delay in ms.',
        propTypeProp: 'NumberShape',
        propTypeVal: '{\n  show: 0,\n  hide: 0\n}',
        propTypeIsRequired: false,
      },
      {
        title: 'modifiers',
        description: 'Popper modifiers object.',
        propTypeProp: 'object',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'noArrow',
        description: 'Whether to hide the arrow, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'target',
        description: 'The target element.',
        propTypeProp: 'Custom',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'placement',
        description: 'The popover placement.',
        propTypeProp: 'string',
        propTypeVal: 'top',
        propTypeIsRequired: false,
      },
      {
        title: 'arrowClassName',
        description: 'The arrow class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'disabled',
        description: 'Whether the popover is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'boundariesElement',
        description: 'The boundaries element for the Popover instance.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'placementPrefix',
        description: 'The placement prefix.',
        propTypeProp: 'string',
        propTypeVal: 'bs-popover',
        propTypeIsRequired: false,
      },
      {
        title: 'open',
        description: 'Whether the popover is open, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Dropdown',
    href: 'https://designrevision.com/docs/shards-react/component/dropdown',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'disabled',
        description: 'Whether it is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'nav',
        description: 'Whether it is located inside a Nav, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'dropup',
        description: 'Whether it is a drop-up, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'open',
        description: 'Whether it is open, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'toggle',
        description: 'The toggle function.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'direction',
        description: 'The direction.',
        propTypeProp: 'enum',
        propTypeVal: 'down',
        propTypeIsRequired: false,
      },
      {
        title: 'inNavbar',
        description: 'Whether it is located inside a navbar, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'DropdownItem',
    href: 'https://designrevision.com/docs/shards-react/component/dropdown',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'active',
        description: 'Whether it is active, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'disabled',
        description: 'Whether it is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'divider',
        description: 'Whether it is a divider, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'header',
        description: 'Whether it is a dropdown header item, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onClick',
        description: 'The function that should be triggered on click.',
        propTypeProp: 'function',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'toggle',
        description: 'The toggle function.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'String | Func',
        propTypeVal: 'button',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'DropdownMenu',
    href: 'https://designrevision.com/docs/shards-react/component/dropdown',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'persist',
        description: 'Whether it should persist, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'modifiers',
        description: 'The modifiers config object.',
        propTypeProp: 'object',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'small',
        description: 'Whether the dropdown is small, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'flip',
        description: 'Whether it should flip, or not.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'right',
        description: 'Whether it is positioned on the right side, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'DropdownToggle',
    href: 'https://designrevision.com/docs/shards-react/component/dropdown',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'caret',
        description: 'Whether it should display a caret, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: 'primary',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'disabled',
        description: 'Whether it is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onClick',
        description: 'The function that should be triggered on click.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'aria-haspopup',
        description: 'The aria-haspopup attribute.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'split',
        description: 'Whether it is split, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'nav',
        description: 'Whether it is located inside a nav, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'String | Func',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Button',
    href: 'https://designrevision.com/docs/shards-react/component/button',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'squared',
        description: 'Whether it is squared, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'pill',
        description: 'Whether it is pill, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'disabled',
        description: 'Whether it is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: 'primary',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'active',
        description: 'Whether it is active, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'block',
        description:
          'Whether it should be displayed as a block (full-width), or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.\n@type {[type]}',
        propTypeProp: 'ObjectFuncString',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'FuncString',
        propTypeVal: 'button',
        propTypeIsRequired: false,
      },
      {
        title: 'size',
        description: 'The size.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'outline',
        description: 'Whether it is outline, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Modal',
    href: 'https://designrevision.com/docs/shards-react/component/modal',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'size',
        description: 'The size.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'Array[Node]Node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'fade',
        description: 'Whether it should fade, or not.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'showModal',
        description:
          'The function that should be triggered when the modal is shown.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'backdrop',
        description: 'Whether it should display a backdrop, or not.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'backdropClassName',
        description: 'The class name for the backdrop element.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'id',
        description: 'The id.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'position',
        description: 'The position.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'modalContentClassName',
        description: 'The class name for the modal content.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tabIndex',
        description: 'The tab index.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'animation',
        description: '',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'hiddenModal',
        description:
          'The function that should be triggered when the modal is finally hidden.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'role',
        description: 'The role attribute for the modal.',
        propTypeProp: 'string',
        propTypeVal: 'dialog',
        propTypeIsRequired: false,
      },
      {
        title: 'toggle',
        description: 'The toggle function.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'open',
        description: 'Whether it is open, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'modalClassName',
        description: 'The class name for the modal.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'centered',
        description: 'Whether it should be centered, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'hideModal',
        description:
          'The function that should be triggered when the modal is set to hide.',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Nav',
    href: 'https://designrevision.com/docs/shards-react/component/nav',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'horizontal',
        description: 'Justify content horizontally.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'FuncString',
        propTypeVal: 'ul',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'card',
        description: 'Whether it is located inside a card, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'navbar',
        description: 'Whether it is located inside a Navbar, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tabs',
        description: 'Whether it should be displayed as tabs, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'fill',
        description: 'Whether it should fill the entire space, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'vertical',
        description: 'Whether it is vertical, or not.',
        propTypeProp: 'BoolString',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'pills',
        description: 'Whether it should be displayed as pills, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'justified',
        description: 'Whether it is justified, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormSelect',
    href: 'https://designrevision.com/docs/shards-react/component/form-select',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'invalid',
        description: 'Whether it is invalid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'size',
        description: 'The size.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'valid',
        description: 'Whether it is valid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'ObjectFuncString',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Card',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'outline',
        description: 'Whether it is outline, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'small',
        description: 'Whether the card is small, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'FuncString',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'StringObjectFunc',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardBody',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'Array[Node] | Node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardColumns',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardDeck',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardFooter',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardGroup',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardHeader',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardImg',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'top',
        description:
          'Whether the image is positioned at the top of the card, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'bottom',
        description:
          'Whether the image is positioned at the bottom of the card, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'img',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardImgOverlay',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardLink',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'a',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'String | Object | Func',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardSubtitle',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'h6',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardText',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'a',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'CardTitle',
    href: 'https://designrevision.com/docs/shards-react/component/card',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'Func | String',
        propTypeVal: 'h5',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'ButtonGroup',
    href: 'https://designrevision.com/docs/shards-react/component/button-group',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'size',
        description: 'The size.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'vertical',
        description: 'Whether it is vertical, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Badge',
    href: 'https://designrevision.com/docs/shards-react/component/badge',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: 'primary',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The component tag.',
        propTypeProp: 'FuncString',
        propTypeVal: 'span',
        propTypeIsRequired: false,
      },
      {
        title: 'pill',
        description: 'Whether it should be a pill, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'outline',
        description: 'Whether it should be outlined, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Progress',
    href: 'https://designrevision.com/docs/shards-react/component/progress',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'value',
        description: 'The value.',
        propTypeProp: 'StringNumber',
        propTypeVal: 0,
        propTypeIsRequired: false,
      },
      {
        title: 'barClassName',
        description: 'The class name for the bar element.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: 'primary',
        propTypeIsRequired: false,
      },
      {
        title: 'max',
        description: 'The max value.',
        propTypeProp: 'StringNumber',
        propTypeVal: 100,
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'striped',
        description: 'Whether it is striped, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'animated',
        description: 'Whether it is animated, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'bar',
        description: 'Whether it is a bar, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'multi',
        description: 'Whether there are multiple progress bars nested, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Fade',
    href: 'https://designrevision.com/docs/shards-react/component/fade',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'innerRef',
        description: '',
        propTypeProp: 'ObjectStringFunc',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'baseClass',
        description: '',
        propTypeProp: 'string',
        propTypeVal: 'fade',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: '',
        propTypeProp: 'StringFunc',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'exit',
        description: '',
        propTypeProp: '',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'timeout',
        description: '',
        propTypeProp: '',
        propTypeVal: 'TIMEOUT.FADE',
        propTypeIsRequired: false,
      },
      {
        title: 'enter',
        description: '',
        propTypeProp: '',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'baseClassActive',
        description: '',
        propTypeProp: 'string',
        propTypeVal: 'show',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: '',
        propTypeProp: 'Array[Node]Node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: '',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'appear',
        description: '',
        propTypeProp: '',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'in',
        description: '',
        propTypeProp: '',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormTextarea',
    href: 'https://designrevision.com/docs/shards-react/component/form-textarea',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'ObjectFuncString',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'plaintext',
        description: 'Whether it should be displayed as plain text, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'valid',
        description: 'Whether it is valid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'invalid',
        description: 'Whether it is invalid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'size',
        description: 'The size.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Navbar',
    href: 'https://designrevision.com/docs/shards-react/component/navbar',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'role',
        description: 'The role attribute.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'FuncString',
        propTypeVal: 'nav',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: 'The theme color.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'expand',
        description: 'Whether it should expand, or not.',
        propTypeProp: 'BoolString',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'sticky',
        description: 'Whether it is sticky, or not.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'fixed',
        description: 'Whether it is fixed, or not.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'type',
        description: 'The navbar type.',
        propTypeProp: 'enum',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'full',
        description: 'Whether it is full, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name attribute.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Tooltip',
    href: 'https://designrevision.com/docs/shards-react/component/tooltip',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'placementPrefix',
        description: 'The placement prefix.',
        propTypeProp: 'string',
        propTypeVal: 'bs-tooltip',
        propTypeIsRequired: false,
      },
      {
        title: 'boundariesElement',
        description: 'The boundaries element for the tooltip instance.',
        propTypeProp: 'StringElement',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerClassName',
        description: 'The tooltip inner class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'toggle',
        description: 'The toggle function.',
        propTypeProp: 'function',
        propTypeVal: 'function() {}',
        propTypeIsRequired: false,
      },
      {
        title: 'delay',
        description: 'The show/hide delay in ms.',
        propTypeProp: 'NumberShape',
        propTypeVal: '{\n  show: 0,\n  hide: 0\n}',
        propTypeIsRequired: false,
      },
      {
        title: 'autohide',
        description: 'Whether the tooltip should auto-hide, or not.',
        propTypeProp: 'boolean',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'noArrow',
        description: 'Whether to hide the arrow, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'placement',
        description: 'The tooltip placement.',
        propTypeProp: 'enum',
        propTypeVal: 'top',
        propTypeIsRequired: false,
      },
      {
        title: 'trigger',
        description: 'The trigger(s) (click, hover, focus).',
        propTypeProp: 'string',
        propTypeVal: 'hover',
        propTypeIsRequired: false,
      },
      {
        title: 'target',
        description: 'The target element.',
        propTypeProp: 'Custom',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'container',
        description: 'The tooltip container.',
        propTypeProp: 'Custom',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'offset',
        description: 'The tooltip offset.',
        propTypeProp: 'StringNumber',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'open',
        description: 'Whether the tooltip is open, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The tooltip class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'arrowClassName',
        description: 'The arrow class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'modifiers',
        description: 'Popper modifiers object.',
        propTypeProp: 'object',
        propTypeVal: '',
        propTypeIsRequired: false,
      },

      {
        title: 'disabled',
        description: 'Whether the tooltip is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Form',
    href: 'https://designrevision.com/docs/shards-react/component/form',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: 'form',
        propTypeIsRequired: false,
      },
      {
        title: 'inline',
        description: 'Whether it is inline, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormFeedback',
    href: 'https://designrevision.com/docs/shards-react/component/form',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'tooltip',
        description: 'Whether the feedback should be displayed as tooltip.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'valid',
        description: 'Whether the feedback is valid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: 'undefined',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormGroup',
    href: 'https://designrevision.com/docs/shards-react/component/form-group',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'inline',
        description: 'Whether it is displayed inline (form check) or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'row',
        description: 'Whether it is a row, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The components' tag type.",
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'check',
        description: 'Whether it is a form check, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'disabled',
        description: 'Whether it is disabled, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Breadcrumb',
    href: 'https://designrevision.com/docs/shards-react/component/breadcrumb',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'tag',
        description: 'The component tag name.',
        propTypeProp: 'string',
        propTypeVal: 'nav',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'aria-label',
        description: 'The aria label value.',
        propTypeProp: 'string',
        propTypeVal: 'breadcrumb',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'listTag',
        description: 'The breadcrumb list tag.',
        propTypeProp: 'string',
        propTypeVal: 'ol',
        propTypeIsRequired: false,
      },
      {
        title: 'listClassName',
        description: 'The breadcrumb list class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'BreadcrumbItem',
    href: 'https://designrevision.com/docs/shards-react/component/breadcrumb',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'tag',
        description: 'The component tag name.',
        propTypeProp: 'string',
        propTypeVal: 'nav',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'active',
        description: 'Whether it is active, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'InputGroup',
    href: 'https://designrevision.com/docs/shards-react/component/input-group',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'size',
        description: 'The size.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'seamless',
        description: 'Whether it is seamless, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The tag type.',
        propTypeProp: 'FuncString',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'InputGroupAddon',
    href: 'https://designrevision.com/docs/shards-react/component/input-group',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'type',
        description: 'The addon type.',
        propTypeProp: 'enum',
        propTypeVal: '',
        propTypeIsRequired: true,
      },
      {
        title: 'tag',
        description: 'The tag type.',
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'InputGroupText',
    href: 'https://designrevision.com/docs/shards-react/component/input-group',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The tag type.',
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormInput',
    href: 'https://designrevision.com/docs/shards-react/component/form-input',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'type',
        description: 'The input type.',
        propTypeProp: 'enum',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'plaintext',
        description: 'Whether it is plaintext, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'size',
        description: "The input's size.",
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'inline',
        description: 'Whether it is inline, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'valid',
        description: 'Whether it is valid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'invalid',
        description: 'Whether it is invalid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Slider',
    href: 'https://designrevision.com/docs/shards-react/component/slider',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'behaviour',
        description: '',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'cssPrefix',
        description: '',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'margin',
        description: '',
        propTypeProp: 'number',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'orientation',
        description: '',
        propTypeProp: 'enum',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'disabled',
        description: '',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'step',
        description: '',
        propTypeProp: 'number',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'range',
        description: '',
        propTypeProp: 'object',
        propTypeVal: '',
        propTypeIsRequired: true,
      },
      {
        title: 'connect',
        description: '',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tooltips',
        description: '',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'limit',
        description: '',
        propTypeProp: 'number',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onStart',
        description: '',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'direction',
        description: '',
        propTypeProp: 'enum',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onSlide',
        description: '',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onChange',
        description: '',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'pips',
        description: '',
        propTypeProp: 'object',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'start',
        description: '',
        propTypeProp: 'Array',
        propTypeVal: '',
        propTypeIsRequired: true,
      },
      {
        title: 'className',
        description: '',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onUpdate',
        description: '',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onSet',
        description: '',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'animate',
        description: '',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onEnd',
        description: '',
        propTypeProp: 'function',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'theme',
        description: '',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormCheckbox',
    href: 'https://designrevision.com/docs/shards-react/component/form-checkbox',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'small',
        description: 'Whether it is small (toggle), or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'invalid',
        description: 'Whether it is invalid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onChange',
        description: 'The onChange handler.',
        propTypeProp: 'function',
        propTypeVal: '() => {}',
        propTypeIsRequired: false,
      },
      {
        title: 'inline',
        description: 'Whether it is inline, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'toggle',
        description: 'Whether it is a toggle button, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'valid',
        description: 'Whether it is valid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'Collapse',
    href: 'https://designrevision.com/docs/shards-react/component/collapse',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'children',
        description: 'The children components.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'timeout',
        description: '',
        propTypeProp: '',
        propTypeVal: 'TIMEOUT.COLLAPSE',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'navbar',
        description: 'Whether it is located inside a navbar, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'enter',
        description: '',
        propTypeProp: '',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'appear',
        description: '',
        propTypeProp: '',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
      {
        title: 'exit',
        description: '',
        propTypeProp: '',
        propTypeVal: true,
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: 'The element tag type.',
        propTypeProp: 'string',
        propTypeVal: 'div',
        propTypeIsRequired: false,
      },
      {
        title: 'open',
        description: 'Whether it is open, or not.',
        propTypeProp: 'boolean',
        propTypeVal: false,
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'ListGroup',
    href: 'https://designrevision.com/docs/shards-react/component/list-group',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'flush',
        description: 'Whether the list group should be flushed, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'small',
        description: 'Whether the list group is small, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'tag',
        description: "The component's tag type.",
        propTypeProp: 'string',
        propTypeVal: 'ul',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'FormRadio',
    href: 'https://designrevision.com/docs/shards-react/component/form-radio',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'children',
        description: 'The children.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'valid',
        description: 'Whether it is valid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'innerRef',
        description: 'The inner ref.',
        propTypeProp: 'string',
        propTypeVal: 'object | function | string',
        propTypeIsRequired: false,
      },
      {
        title: 'inline',
        description: 'Whether it is inline, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'invalid',
        description: 'Whether it is invalid, or not.',
        propTypeProp: 'boolean',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'onChange',
        description: 'The function that should run on change.',
        propTypeProp: 'function',
        propTypeVal: '() => {}',
        propTypeIsRequired: false,
      },
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
  {
    title: 'ButtonToolbar',
    href: 'https://designrevision.com/docs/shards-react/component/button-toolbar',
    description: '',
    isActive: true,
    isPublic: true,
    componentImport: 'shards-react',
    ispropTypeVal: false,
    provider: '60ce6f27812f5f51bc2f7ed0',
    techno: '5ee7b6b97127c03650219837',
    uid: '5ee6c9e92af38140dc55cc5b',
    propType: '5ee7b8b6a426614c8c02d0ed',
    componentProps: [
      {
        title: 'className',
        description: 'The class name.',
        propTypeProp: 'string',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
      {
        title: 'children',
        description: 'The children nodes.',
        propTypeProp: 'node',
        propTypeVal: '',
        propTypeIsRequired: false,
      },
    ],
  },
]
